services:
  postgres:
    image: postgres:16
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_USER: userService
      POSTGRES_PASSWORD: ALpngaUj4Ab7
      POSTGRES_DB: OBRIO
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  user-service:
    build: ./user-service
    env_file:
      - ./user-service/.env
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 3000:3000

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: password
    build: ./rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  db-data: